// ─────────────────────────────────────────────
//  redop — core types
// ─────────────────────────────────────────────

// ── JSON-RPC / MCP wire types ─────────────────

export interface JsonRpcRequest {
  id: string | number | null;
  jsonrpc: "2.0";
  method: string;
  params?: Record<string, unknown>;
}

export interface JsonRpcResponse {
  error?: { code: number; message: string; data?: unknown };
  id: string | number | null;
  jsonrpc: "2.0";
  result?: unknown;
}

export interface McpToolCallParams {
  arguments?: Record<string, unknown>;
  name: string;
}

export interface McpContent {
  data?: string;
  mimeType?: string;
  text?: string;
  type: "text" | "image" | "resource";
}

export interface McpToolResult {
  content: McpContent[];
  isError?: boolean;
}

export enum McpErrorCode {
  ParseError = -32_700,
  InvalidRequest = -32_600,
  MethodNotFound = -32_601,
  InvalidParams = -32_602,
  InternalError = -32_603,
  // MCP-specific
  ToolNotFound = -32_000,
  ValidationFailed = -32_001,
  Unauthorized = -32_002,
  RateLimited = -32_003,
  Timeout = -32_004,
}

export class McpError extends Error {
  constructor(
    public readonly code: McpErrorCode,
    message: string,
    public readonly data?: unknown
  ) {
    super(message);
    this.name = "McpError";
  }
}

// ── Request / context ─────────────────────────

export type TransportKind = "http" | "stdio" | "ws";

/**
 * Normalized transport metadata for the current tool invocation.
 */
export interface ToolRequest {
  /** Lowercased request headers. */
  headers: Record<string, string>;
  /** Client IP when the active transport can provide it. */
  ip?: string;
  /** HTTP method for HTTP transport requests. */
  method?: string;
  /** Raw HTTP Request object when transport = `http`. */
  raw?: Request;
  /** MCP session id for streamable HTTP sessions. */
  sessionId?: string;
  /** Active transport handling the request. */
  transport: TransportKind;
  /** Full request URL for HTTP transport requests. */
  url?: string;
}

export type RequestMeta = ToolRequest;

/**
 * Mutable bag threaded through every hook for a single request.
 * Extend with your own fields via the generic parameter.
 *
 * @example
 * type AppCtx = Context<{ userId: string; startedAt: number }>
 */
export type Context<
  T extends Record<string, unknown> = Record<string, unknown>,
> = {
  /** Lowercased request headers mirrored from `request.headers`. */
  headers: Record<string, string>;
  /** Per-request unique id generated by redop. */
  requestId: string;
  /** MCP session id for streamable HTTP sessions. */
  sessionId?: string;
  /** Fully resolved tool name. */
  tool: string;
  /** Active transport handling the request. */
  transport: TransportKind;
  /** Raw tool arguments before schema parsing. */
  rawParams: Record<string, unknown>;
} & T;

// ── Tool event model ──────────────────────────

/**
 * Event object passed to every tool handler.
 */
export interface ToolHandlerEvent<I = unknown, C extends Context = Context> {
  /** Shared mutable per-request state. */
  ctx: C;
  /** Parsed tool input after schema validation/coercion. */
  input: I;
  /** Read-only transport metadata for the current invocation. */
  request: ToolRequest;
  /** Fully resolved tool name. */
  tool: string;
}

/**
 * Event object passed to a tool-local `before` hook.
 */
export interface ToolBeforeHookEvent<I = unknown, C extends Context = Context> {
  /** Shared mutable per-request state. */
  ctx: C;
  /** Parsed tool input after schema validation/coercion. */
  input: I;
  /** Read-only transport metadata for the current invocation. */
  request: ToolRequest;
  /** Fully resolved tool name. */
  tool: string;
}

/**
 * Event object passed to a tool-local `after` hook.
 */
export interface ToolAfterHookEvent<
  I = unknown,
  R = unknown,
  C extends Context = Context,
> extends ToolBeforeHookEvent<I, C> {
  /** Successful result returned by middleware/handler before global after hooks. */
  result: R;
}

export type ToolHandler<I, O = unknown, C extends Context = Context> = (
  event: ToolHandlerEvent<I, C>
) => O | Promise<O>;

export type ToolNext<R = unknown> = () => Promise<R>;

/**
 * Event object passed to middleware.
 */
export interface ToolMiddlewareEvent<
  I = unknown,
  C extends Context = Context,
  R = unknown,
> extends ToolHandlerEvent<I, C> {
  /** Continue to the next middleware or final handler. */
  next: ToolNext<R>;
}

export type ToolMiddleware<
  I = unknown,
  R = unknown,
  C extends Context = Context,
> = (event: ToolMiddlewareEvent<I, C, R>) => R | Promise<R>;

export type ToolBeforeHook<I = unknown, C extends Context = Context> = (
  event: ToolBeforeHookEvent<I, C>
) => void | Promise<void>;

export type ToolAfterHook<
  I = unknown,
  R = unknown,
  C extends Context = Context,
> = (event: ToolAfterHookEvent<I, R, C>) => void | Promise<void>;

// ── Plugin model ──────────────────────────────

/**
 * Descriptive metadata for reusable plugins.
 */
export interface PluginMeta {
  description?: string;
  name: string;
  version: string;
}

/**
 * Definition object used by `definePlugin(...)`.
 */
export interface PluginDefinition<Options, C extends Context = Context>
  extends PluginMeta {
  /** Create a plugin instance from a single options object. */
  setup: (options: Options) => import("./redop").Redop<C>;
}

/**
 * Callable plugin factory with attached metadata for docs and introspection.
 */
export interface PluginFactory<Options, C extends Context = Context> {
  meta: PluginMeta;
  (options: Options): import("./redop").Redop<C>;
}

// ── Hook event shapes ─────────────────────────

export interface BeforeHookEvent<C extends Context = Context, I = unknown> {
  ctx: C;
  input: I;
  params: I;
  request: ToolRequest;
  tool: string;
}

export interface AfterHookEvent<
  C extends Context = Context,
  R = unknown,
  I = unknown,
> {
  ctx: C;
  input: I;
  params: I;
  request: ToolRequest;
  result: R;
  tool: string;
}

export interface ErrorHookEvent<C extends Context = Context, I = unknown> {
  ctx: C;
  error: unknown;
  input: I;
  params: I;
  request: ToolRequest;
  tool: string;
}

export interface TransformHookEvent<C extends Context = Context> {
  ctx: C;
  params: Record<string, unknown>;
  request: ToolRequest;
  tool: string;
}

// ── Hook function types ───────────────────────

export type BeforeHook<C extends Context = Context> = (
  event: BeforeHookEvent<C>
) => void | Promise<void>;

export type AfterHook<C extends Context = Context, R = unknown> = (
  event: AfterHookEvent<C, R>
) => void | Promise<void>;

export type ErrorHook<C extends Context = Context> = (
  event: ErrorHookEvent<C>
) => void | Promise<void>;

export type TransformHook<C extends Context = Context> = (
  event: TransformHookEvent<C>
) => void | Record<string, unknown> | Promise<void | Record<string, unknown>>;

export type MapResponseHook<R = unknown> = (
  result: R,
  tool: string
) => unknown | Promise<unknown>;

// ── Schema typing / adapters ─────────────────

export interface StandardSchemaResultSuccess<Output> {
  readonly issues?: undefined;
  readonly value: Output;
}

export interface StandardSchemaIssue {
  readonly message: string;
  readonly path?: ReadonlyArray<PropertyKey | { readonly key: PropertyKey }>;
}

export interface StandardSchemaResultFailure {
  readonly issues: ReadonlyArray<StandardSchemaIssue>;
}

export interface StandardSchemaJsonOptions {
  readonly libraryOptions?: Record<string, unknown>;
  readonly target: string;
}

export interface StandardSchemaV1<Input = unknown, Output = Input> {
  readonly "~standard": {
    readonly jsonSchema?: {
      readonly input: (
        options: StandardSchemaJsonOptions
      ) => Record<string, unknown>;
      readonly output: (
        options: StandardSchemaJsonOptions
      ) => Record<string, unknown>;
    };
    readonly validate: (
      value: unknown,
      options?: { readonly libraryOptions?: Record<string, unknown> }
    ) =>
      | StandardSchemaResultSuccess<Output>
      | StandardSchemaResultFailure
      | Promise<
          StandardSchemaResultSuccess<Output> | StandardSchemaResultFailure
        >;
    readonly types?: {
      readonly input: Input;
      readonly output: Output;
    };
    readonly vendor: string;
    readonly version: 1;
  };
}

export type InferSchemaOutput<S> =
  S extends StandardSchemaV1<any, infer Output>
    ? Output
    : S extends Record<string, unknown>
      ? Record<string, unknown>
      : unknown;

/**
 * Implement this interface to plug any schema library into redop.
 *
 * @example
 * const zodAdapter: SchemaAdapter<ZodTypeAny> = {
 *   toJsonSchema: (s) => zodToJsonSchema(s),
 *   parse:        (s, input) => s.parse(input),
 * }
 */
export interface SchemaAdapter<S = unknown, Parsed = InferSchemaOutput<S>> {
  /** Runtime parse + coerce. Throw on failure. */
  parse(schema: S, input: unknown): Parsed | Promise<Parsed>;
  /** Convert schema to JSON Schema for MCP tool descriptions */
  toJsonSchema(schema: S): Record<string, unknown>;
}

// ── Tool definition ───────────────────────────

/**
 * Definition object for a single MCP tool.
 */
export interface ToolDef<
  S = unknown,
  I = InferSchemaOutput<S>,
  C extends Context = Context,
  O = unknown,
> {
  /** Tool-local hook that runs after middleware/handler success and before global after hooks. */
  after?: ToolAfterHook<I, O, C>;
  /** MCP tool annotations surfaced to compatible clients. */
  annotations?: {
    title?: string;
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    idempotentHint?: boolean;
    openWorldHint?: boolean;
  };
  /** Tool-local hook that runs after global before hooks and before middleware. */
  before?: ToolBeforeHook<I, C>;
  /** Human-friendly tool description shown in tool listings. */
  description?: string;
  /** Tool handler receiving parsed input, shared context, and request metadata. */
  handler: ToolHandler<I, O, C>;
  /** Schema instance (Zod, TypeBox, etc.) or plain JSON Schema object */
  input?: S;
}

export interface ResolvedTool {
  after?: ToolAfterHook<unknown, unknown>;
  annotations?: Record<string, unknown>;
  before?: ToolBeforeHook<unknown>;
  description?: string;
  handler: ToolHandler<unknown>;
  inputSchema: Record<string, unknown>;
  name: string;
}

// ── Transport / listen options ────────────────

/**
 * CORS configuration for the HTTP transport.
 */
export interface CorsOptions {
  /** Whether browsers may send credentials. Default: `true`. */
  credentials?: boolean;
  /** Allowed request headers. Default includes content type, auth, API key, and session id headers. */
  headers?: string[];
  /** Allowed HTTP methods. Default: `GET, POST, DELETE, OPTIONS`. */
  methods?: string[];
  /** Allowed origins. Default: `"*"`. */
  origins?: string | string[];
}

export type TlsOptions = import("bun").TLSOptions;

export interface ServerInfoOptions {
  name?: string;
  version?: string;
}

/**
 * Constructor options for `new Redop(...)`.
 */
export interface RedopOptions {
  /** MCP server identity advertised during initialize. Default: `"redop"`. */
  name?: string;
  /** Custom schema adapter. By default, redop auto-detects supported schemas. */
  schemaAdapter?: SchemaAdapter;
  /** MCP server version advertised during initialize. Default: `"0.1.0"`. */
  version?: string;
}

/**
 * Runtime options for `app.listen(...)`.
 */
export interface ListenOptions {
  /** CORS — true = permissive dev mode. */
  cors?: boolean | CorsOptions;
  /** Bind address. "0.0.0.0" for all interfaces. */
  hostname?: string;
  /** Max request body in bytes. Default 4MB. */
  maxBodySize?: number;
  /** Fires once the server is bound. */
  onListen?: (info: { hostname: string; port: number; url: string }) => void;
  /** MCP mount path. Defaults to "/mcp". */
  path?: string;
  /** TCP port (HTTP / WS only). Defaults to 3000. */
  port?: number | string;
  /** Idle session TTL in ms. Default 30_000. */
  sessionTimeout?: number;
  /** Bun TLS config */
  tls?: TlsOptions;
  /** Transport protocol. Auto-detects if omitted. */
  transport?: TransportKind;
}
